# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: demoapp # Deploy to demoapp namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx # Sets the 'app=nginx' label for Alloy relabeling
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
